server:
    port: 8080

spring:
    application:
        name: tddboutique

    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://localhost:3306/tddboutique?autoReconnect=true&useSSL=false
        username: root
        password:

    jpa:
        database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: validate
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            
    # MultipartProperties: Enable multipart uploads
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB    # Threshold after which files are written to disk.
            max-file-size: 25MB         # Max file size.
            max-request-size: 100MB # Max Request Size

# File Storage Properties
# All files uploaded through the REST API will be stored in this directory
file:
    uploadDir: ${java.io.tmpdir}tddboutique\images

app:
    name: tddboutique

# Disable the spring security default configuration from spring-boot-actuator
management:
    security:
        enabled: true
security:
    basic:
        enabled: false

jwt:
    header: authorization
    # Token is valid for 24 hours
    expiresIn: 86400
    secret: thisissomerandomsecret32
    cookie: AUTH-TOKEN

